---
title: "30_conhecimento_codigo"
author: "Victor Elias"
date: "28/01/2022"
output: html_document
---

# Bibliotecas
```{r}
library(tidyverse)
library(ggplot2)
library(plotly)
```


# Lê os dados
```{r}
planetas <- read.csv("data/exoplanetas.csv")
```


# Bases
```{r}

data <- planetas %>% 
  select(X..name, discovered, planet_status, mass, radius,
         orbital_period, molecules, updated, star_name, inclination,
         detection_type, alternate_names)

# Renomeação de data
data <- data %>% 
  rename(
    name = X..name,
    descoberto = discovered,
    status = planet_status,
    massa = mass,
    radio = radius,
    periodo_orbital = orbital_period,
    moleculas = molecules,
    atualizado = updated,
    nome_estrela = star_name,
    inclinacao = inclination,
    tipo_deteccao = detection_type,
    nome_alternativo = alternate_names
  )

data <- data %>% 
  filter(!is.na(descoberto)) %>% 
  replace_na(list(periodo_orbital = "Sem atualização"))


# Tentar fazer código que separa as palavras.
# temp <- data %>% 
#   select(moleculas) %>% 
#   unique() %>% 
#   unnest_tokens() %>% 

data <- data %>% 
  mutate(descoberto = as.numeric(descoberto))

# temp <- data %>% 
#   select(moleculas) %>%
#   count(moleculas)

temp_plot <- data %>% 
  head(50) %>% 
  ggplot(aes(x = massa, y = name, size = massa)) +
  geom_point() +
  theme(
    axis.text.y = element_text(margin = margin(t = 5)),
    axis.title.x = element_text(margin = margin(t = 20))
  )
temp_plot

# Dez primeiros (em ordem alfabética) - Teste
plot <- data %>% 
  head(10) %>% 
  arrange(massa) %>% 
  ggplot(aes(massa, name)) +
  labs(x = "Massa", y = "Nome",
       title = "Dez primeiros planetas da base de dados.",
       caption = "Gerado em ggplot por Victor Elias") +
  geom_col(fill = "#fc033d") +
  theme(
    axis.title.y = element_text(margin = margin(t = 5)),
    axis.title.x = element_text(margin = margin(t = 20))
  )

plot
```




